---
name: Warema WMS Bridge
version: "2.1.2"
slug: addon-warema-bridge
description: "Bridge for Warema WMS devices with MQTT support"
url: "https://github.com/chha25/addon-warema-bridge"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: "services"
boot: "auto"
init: false
icon: "icon.png"

map:
  config: true

devices:
  - /dev/ttyUSB0

options:
  mqtt_server: "mqtt://core-mosquitto:1883"
  mqtt_user: ""
  mqtt_password: ""
  log_level: "info"
  wms_serial_port: "/dev/ttyUSB0"
  wms_key: ""
  wms_pan_id: "FFFF"
  wms_channel: 17
  ignored_devices: ""
  force_devices: ""

schema:
  mqtt_server: str?
  mqtt_user: str?
  mqtt_password: password?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  wms_serial_port: device(subsystem=tty)
  wms_key: password?
  wms_pan_id: str?
  wms_channel: int?
  ignored_devices: str?
  force_devices: str?

services:
  - "mqtt:need"
